---
deployment:
  tasks:
    - export DEPLOY_STATIC = /home/glowspac/public_html
    - export DEPLOY_TO_AGORA = /home/glowspace/Glow2/Agora
    - export DEPLOY_TO_AGORAPROJ = /home/glowspace/Glow2/AgoraProj
    
    - /bin/cp -r Agora/static $DEPLOY_STATIC
    - /bin/cp -r Agora $DEPLOY_TO_AGORA
    - /bin/cp -r Agora $DEPLOY_TO_AGORAPROJ

    