# Generated by Django 5.0.4 on 2024-04-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=400)),
                ('gender', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=600)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('profile_photo', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=255)),
            ],
        ),
    ]
