# Generated by Django 5.0.4 on 2024-04-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0002_remove_account_email_remove_account_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='auth_user_ID',
            new_name='auth_user',
        ),
    ]
