# Generated by Django 5.0.4 on 2024-04-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0003_rename_auth_user_id_account_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.URLField(verbose_name='File Url'),
        ),
    ]
