# Generated by Django 5.0.4 on 2024-04-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0004_alter_account_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
    ]
