# Generated by Django 5.0.4 on 2024-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0006_account_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='UIAppearance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
