# Generated by Django 5.0.4 on 2024-05-03 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0008_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=800)),
                ('dateTime', models.DateTimeField()),
                ('account_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agora.account')),
                ('audience_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agora.audience')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('link', models.URLField(verbose_name='File Url')),
                ('dateTime', models.DateTimeField()),
                ('post_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agora.post')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('link', models.URLField(verbose_name='File Url')),
                ('dateTime', models.DateTimeField()),
                ('post_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agora.post')),
            ],
        ),
    ]
