# Generated by Django 5.0.4 on 2024-05-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0009_post_photo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
