# Generated by Django 5.0.4 on 2024-05-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0010_remove_photo_name_remove_video_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='post_ID',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='account_ID',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='audience_ID',
            new_name='audience',
        ),
    ]
