# Generated by Django 5.0.4 on 2024-05-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0013_alter_photo_datetime_alter_post_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='link',
            field=models.URLField(null=True, verbose_name='File Url'),
        ),
    ]
