# Generated by Django 5.0.4 on 2024-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0015_remove_photo_datetime_remove_video_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
