# Generated by Django 5.0.4 on 2024-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0022_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
