# Generated by Django 5.0.4 on 2024-05-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0025_alter_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='date_friend_request',
            field=models.TextField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='date_became_friends',
            field=models.TextField(max_length=75, null=True),
        ),
    ]
