# Generated by Django 5.0.4 on 2024-05-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0027_notification_frien_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='frien_request',
            new_name='friend_request',
        ),
    ]
