# Generated by Django 5.0.4 on 2024-05-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0028_rename_frien_request_notification_friend_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
