# Generated by Django 5.0.4 on 2024-05-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0029_remove_notification_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
    ]
