# Generated by Django 5.0.4 on 2024-05-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0030_alter_friend_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='friend_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Agora.friend'),
        ),
    ]
