# Generated by Django 5.0.4 on 2024-05-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0032_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateTime',
            field=models.DateTimeField(max_length=75, null=True),
        ),
    ]
