# Generated by Django 5.0.4 on 2024-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0034_alter_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='date_became_friends',
            field=models.DateTimeField(auto_now_add=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='date_friend_request',
            field=models.DateTimeField(auto_now_add=True, max_length=75, null=True),
        ),
    ]
