# Generated by Django 5.0.4 on 2024-05-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0036_remove_tag_post_tag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(null=True, related_name='tags', to='Agora.post'),
        ),
    ]
