# Generated by Django 5.0.4 on 2024-05-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0040_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='caption',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
