# Generated by Django 5.0.4 on 2024-05-15 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0041_share_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='audience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agora.audience'),
        ),
    ]
