# Generated by Django 5.0.4 on 2024-05-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0042_share_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cover_photo',
            field=models.URLField(null=True, verbose_name='File Url'),
        ),
    ]
