# Generated by Django 5.0.6 on 2024-09-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0045_alter_account_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='link_id_imagekit',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
