# Generated by Django 4.0.1 on 2024-09-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0046_photo_link_id_imagekit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tags', to='Agora.Post'),
        ),
    ]
