# Generated by Django 5.0.6 on 2024-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0047_account_is_online_account_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_photo_id_imagekit',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
