# Generated by Django 5.0.6 on 2024-09-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0048_account_profile_photo_id_imagekit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cover_photo_id_imagekit',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
