# Generated by Django 5.0.6 on 2024-11-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0049_account_cover_photo_id_imagekit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='UIAppearance',
            new_name='ui_appearance',
        ),
    ]
