# Generated by Django 5.0.6 on 2024-11-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0050_rename_age_account_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='birthday',
            new_name='Birthday',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ui_appearance',
            new_name='UIAppearance',
        ),
    ]
