# Generated by Django 5.0.6 on 2024-11-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0052_rename_age_account_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='cover_photo',
            field=models.URLField(blank=True, default='', verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cover_photo_id_imagekit',
            field=models.CharField(blank=True, default='', max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.URLField(default='', verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_photo_id_imagekit',
            field=models.CharField(blank=True, default='', max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ui_appearance',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='audience',
            name='audience',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='audience',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='audience',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='date_became_friends',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='date_friend_request',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.URLField(default='', verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='link_id_imagekit',
            field=models.CharField(blank=True, default='', max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='post',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(default='', verbose_name='File URL'),
        ),
    ]
