# Generated by Django 5.0.6 on 2024-11-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0053_alter_account_bio_alter_account_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
