# Generated by Django 5.0.6 on 2024-11-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0054_alter_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
