# Generated by Django 5.0.6 on 2024-11-15 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0056_alter_post_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['auth_user'], name='Agora_accou_auth_us_562597_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='Agora_comme_post_id_1d8112_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['account'], name='Agora_comme_account_3adb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['user', 'friend'], name='Agora_frien_user_id_3a8ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='glow',
            index=models.Index(fields=['post'], name='Agora_glow_post_id_de2dee_idx'),
        ),
        migrations.AddIndex(
            model_name='glow',
            index=models.Index(fields=['account'], name='Agora_glow_account_60f85d_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['post'], name='Agora_photo_post_id_f00310_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['dateTime'], name='Agora_post_dateTim_134e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['post'], name='Agora_share_post_id_a4f39f_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag'], name='Agora_tag_tag_85bef1_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['post'], name='Agora_video_post_id_c6e858_idx'),
        ),
    ]
