# Generated by Django 5.0.6 on 2024-11-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agora', '0057_alter_post_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='Agora_accou_auth_us_562597_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='Agora_comme_post_id_1d8112_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='Agora_comme_account_3adb3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='friend',
            name='Agora_frien_user_id_3a8ab1_idx',
        ),
        migrations.RemoveIndex(
            model_name='glow',
            name='Agora_glow_post_id_de2dee_idx',
        ),
        migrations.RemoveIndex(
            model_name='glow',
            name='Agora_glow_account_60f85d_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='Agora_photo_post_id_f00310_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='Agora_post_dateTim_134e8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='share',
            name='Agora_share_post_id_a4f39f_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='Agora_tag_tag_85bef1_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='Agora_video_post_id_c6e858_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
